// homeScreenStyles.ts
import { StyleSheet, Dimensions, Platform } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF'
    },
    map: {
        ...StyleSheet.absoluteFillObject
    },
    topBar: {
        position: 'absolute',
        top: Platform.OS === 'ios' ? 50 : 40,
        left: 20,
        right: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        zIndex: 10,
    },
    menuButton: {
        backgroundColor: 'white',
        borderRadius: 12,
        width: 46,
        height: 46,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    searchButton: {
        backgroundColor: 'white',
        borderRadius: 12,
        width: 46,
        height: 46,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    markerContainer: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    productImage: {
        width: 42,
        height: 42,
        borderRadius: 21,
        borderWidth: 2,
        borderColor: '#fff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 5,
    },
    calloutContainer: {
        width: 180,
        backgroundColor: 'white',
        borderRadius: 12,
        padding: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 5,
    },
    calloutImage: {
        width: '100%',
        height: 100,
        borderRadius: 8,
        marginBottom: 10,
    },
    calloutTitle: {
        fontWeight: 'bold',
        fontSize: 16,
        marginBottom: 8,
        textAlign: 'center',
    },
    calloutButton: {
        backgroundColor: '#6C5CE7',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    calloutButtonText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 14,
    },
    matchBannerContainer: {
        position: 'absolute',
        bottom: 40,
        left: 20,
        right: 20,
        alignItems: 'center',
    },
    matchBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderRadius: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 10,
        elevation: 6,
        width: '100%',
    },
    matchIconContainer: {
        marginRight: 12,
    },
    matchBannerText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
    },
    sidebar: {
        position: 'absolute',
        left: 0,
        top: 0,
        bottom: 0,
        width: Dimensions.get('window').width * 0.75,
        backgroundColor: 'white',
        zIndex: 20,
        shadowColor: '#000',
        shadowOffset: { width: 2, height: 0 },
        shadowOpacity: 0.15,
        shadowRadius: 10,
        elevation: 10,
        borderTopRightRadius: 24,
        borderBottomRightRadius: 24,
    },
    profileHeader: {
        alignItems: 'center',
        paddingTop: Platform.OS === 'ios' ? 60 : 50,
        paddingBottom: 24,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
        marginBottom: 16,
    },
    profileImageContainer: {
        position: 'relative',
        marginBottom: 16,
    },
    profileImage: {
        width: 100,
        height: 100,
        borderRadius: 50,
        borderWidth: 3,
        borderColor: '#6C5CE7',
    },
    editProfileBadge: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        backgroundColor: '#6C5CE7',
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 3,
        borderColor: 'white',
    },
    userName: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 4,
    },
    userEmail: {
        fontSize: 14,
        color: '#666',
    },
    sidebarItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 16,
        paddingHorizontal: 24,
    },
    sidebarIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: '#6C5CE7',
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 12,
    },
    sidebarItemText: {
        fontSize: 16,
        fontWeight: '500',
    },
    sidebarDivider: {
        height: 1,
        backgroundColor: '#f0f0f0',
        marginVertical: 8,
        marginHorizontal: 24,
    },
    sidebarOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.5)',
        zIndex: 15,
    },
    versionInfo: {
        position: 'absolute',
        bottom: 30,
        width: '100%',
        alignItems: 'center',
    },
    versionText: {
        fontSize: 12,
        color: '#999',
    },
    actionButton: {
        position: 'absolute',
        bottom: 100,
        right: 20,
        zIndex: 10,
        shadowColor: '#6C5CE7',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    actionButtonGradient: {
        width: 58,
        height: 58,
        borderRadius: 29,
        alignItems: 'center',
        justifyContent: 'center',
    },
    actionPanel: {
        position: 'absolute',
        bottom: 170,
        right: 20,
        backgroundColor: 'transparent',
        alignItems: 'flex-end',
        zIndex: 10,
    },
    actionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 8,
        backgroundColor: 'white',
        borderRadius: 18,
        paddingHorizontal: 16,
        paddingVertical: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 6,
        elevation: 4,
    },
    actionIconGradient: {
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 12,
    },
    actionText: {
        fontSize: 15,
        fontWeight: '500',
        marginRight: 8,
    },

    // Modal Styles
    modalOverlay: {
        flex: 1,
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: 'white',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingVertical: 24,
        maxHeight: '80%',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
    },
    closeButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#6C5CE7',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalBody: {
        padding: 24,
    },

    // Radius Modal
    radiusValueContainer: {
        flexDirection: 'row',
        alignItems: 'baseline',
        justifyContent: 'center',
        marginBottom: 24,
    },
    radiusValue: {
        fontSize: 56,
        fontWeight: 'bold',
        color: '#6C5CE7',
    },
    radiusUnit: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#6C5CE7',
        marginLeft: 6,
    },
    radiusSlider: {
        width: '100%',
        height: 40,
    },
    radiusLabels: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 24,
    },
    radiusLabel: {
        color: '#666',
        fontSize: 14,
    },
    radiusDescription: {
        flexDirection: 'row',
        backgroundColor: 'rgba(108, 92, 231, 0.1)',
        padding: 16,
        borderRadius: 16,
        marginBottom: 24,
    },
    radiusDescriptionText: {
        flex: 1,
        marginLeft: 10,
        fontSize: 14,
        color: '#666',
        lineHeight: 20,
    },

    // Filter Modal
    filterCategoryTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 16,
        marginTop: 8,
    },
    filterOptions: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginBottom: 24,
    },
    filterChip: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#6C5CE7',
        marginRight: 12,
        marginBottom: 12,
        backgroundColor: 'transparent',
    },
    filterChipSelected: {
        backgroundColor: '#6C5CE7',
        borderColor: '#6C5CE7',
    },
    filterChipText: {
        color: '#6C5CE7',
        fontWeight: '500',
    },
    filterChipTextSelected: {
        color: 'white',
    },
    sortOptions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 24,
    },
    sortOption: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#6C5CE7',
        flex: 1,
        marginHorizontal: 6,
        justifyContent: 'center',
    },
    sortOptionSelected: {
        backgroundColor: '#6C5CE7',
    },
    sortOptionText: {
        color: '#6C5CE7',
        fontWeight: '500',
        marginLeft: 8,
    },
    sortOptionTextSelected: {
        color: 'white',
    },

    // Common Button
    applyButton: {
        backgroundColor: '#6C5CE7',
        paddingVertical: 16,
        borderRadius: 16,
        alignItems: 'center',
    },
    applyButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
    }
});